// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIGTcZGvLZHFIHxuwQyVSdoaYRXetfXI',
    appId: '1:1007577311656:web:5bdd4b266480b5ef74d59d',
    messagingSenderId: '1007577311656',
    projectId: 'smart-mart-dd5ff',
    authDomain: 'smart-mart-dd5ff.firebaseapp.com',
    storageBucket: 'smart-mart-dd5ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ft98FWCv6sWAqUOY_OnMN_0d2458zMc',
    appId: '1:1007577311656:android:52a9612fd164038a74d59d',
    messagingSenderId: '1007577311656',
    projectId: 'smart-mart-dd5ff',
    storageBucket: 'smart-mart-dd5ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwswKKi2Dz2zU9OLYfTgJbwGorgbfOF_M',
    appId: '1:1007577311656:ios:1653c1f18418071474d59d',
    messagingSenderId: '1007577311656',
    projectId: 'smart-mart-dd5ff',
    storageBucket: 'smart-mart-dd5ff.appspot.com',
    iosBundleId: 'com.example.smartMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwswKKi2Dz2zU9OLYfTgJbwGorgbfOF_M',
    appId: '1:1007577311656:ios:1774adbeb591e5c174d59d',
    messagingSenderId: '1007577311656',
    projectId: 'smart-mart-dd5ff',
    storageBucket: 'smart-mart-dd5ff.appspot.com',
    iosBundleId: 'com.example.smartMart.RunnerTests',
  );
}
